//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERISTICAS_CARRO
    {
        public int CCOdigo { get; set; }
        public Nullable<int> CCodCarro { get; set; }
        public Nullable<int> CCodCaracteristica { get; set; }
    
        public virtual CARACTERISTICA CARACTERISTICA { get; set; }
        public virtual CARRO CARRO { get; set; }
    }
}
