//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRO()
        {
            this.CARACTERISTICAS_CARRO = new HashSet<CARACTERISTICAS_CARRO>();
            this.FOTO = new HashSet<FOTO>();
            this.VENDA = new HashSet<VENDA>();
        }
    
        public int CACodigo { get; set; }
        public Nullable<int> CACodModelo { get; set; }
        public Nullable<int> CAAno { get; set; }
        public string CAPlaca { get; set; }
        public Nullable<decimal> CAPreco { get; set; }
        public Nullable<bool> CAVendido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAS_CARRO> CARACTERISTICAS_CARRO { get; set; }
        public virtual MODELO_CARRO MODELO_CARRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTO> FOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDA> VENDA { get; set; }
    }
}
