//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTO
    {
        public int FOCodigo { get; set; }
        public byte[] FOFoto { get; set; }
        public Nullable<int> FOCodCarro { get; set; }
        public string FOMimeType { get; set; }
    
        public virtual CARRO CARRO { get; set; }
    }
}
