//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECOMMERCE_CARSEntities : DbContext
    {
        public ECOMMERCE_CARSEntities()
            : base("name=ECOMMERCE_CARSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARACTERISTICA> CARACTERISTICA { get; set; }
        public virtual DbSet<CARACTERISTICAS_CARRO> CARACTERISTICAS_CARRO { get; set; }
        public virtual DbSet<CARRO> CARRO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<MARCA_CARRO> MARCA_CARRO { get; set; }

        public virtual DbSet<MODELO_CARRO> MODELO_CARRO { get; set; }
        public virtual DbSet<VENDA> VENDA { get; set; }
    }
}
