//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDA
    {
        public int VECodigo { get; set; }
        public Nullable<int> VECodCarro { get; set; }
        public Nullable<System.DateTime> VEData { get; set; }
        public Nullable<int> VECodCliente { get; set; }
    
        public virtual CARRO CARRO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
